### PR TITLE
feat: Build multi arch container image

### LINKED ISSUE #665: Multi-arch docker image (arm64)
Hi,

**Is your feature request related to a problem? Please describe.**
I can't run the container from dockerhub on my macbook (arm64) without emulation.

**Describe the solution you'd like**

this project looks very cool. I was looking for something like [jenkinsci/build-monitor-plugin](https://github.com/jenkinsci/build-monitor-plugin) for actions, and this looks pretty similar.

One thing I noticed is that only a amd64 image is published on DockerHub. For running on an apple arm, or also on a raspi, it would be useful to publish arm64 too. I'm not sure if the image has anything arch-specific to it, but since it seems to be a pretty standard java spring app I guess it's 'just' a matter of making the x-platform build, presumably using qemu and docker buildx.

**Describe alternatives you've considered**
None

**Additional context**

I might be able to do a pr for that if that is desired.

Best,
Florian

### PR DESCRIPTION
**Pull request by fwilhe2**
This change allows to more easily use the container image aarch computers.

closes #665

### CODE REVIEW

**Comment by sumanmaity1234** [comment]
Hi @fwilhe2,
It's a nice idea to have multi arch container image. 
Can you please update `lib.sh` to build docker image for both the architecture?

**Comment by sumanmaity1234** [comment]
Additionally, as per https://docs.docker.com/build/building/multi-platform/#qemu, the qemu can reduce the speed of docker build. Maybe it'll be better to tryout with `platforms` from https://github.com/docker/setup-buildx-action

**Comment by fwilhe2** [comment]
Hi @sumanmaity1234 

>  Can you please update lib.sh to build docker image for both the architecture?

I'm not sure what the benefit of this would be. My understanding is that `lib.sh` is only used for local development where building for the native cpu architecture is desired.

It could use [docker-buildx](https://docs.docker.com/reference/cli/docker/buildx/build/) cli but that would either need to push the images or 'load' which it will only do for the native architecture, so I don't see the benefit of changing that.

> qemu can reduce the speed of docker build

Interesting, that seems to work but I'm not fully sure how.. Was under the assumption that qemu is needed for system emulation.

I'm not sure how I can easily test this change in CI, so I can't ensure it actually works.

**Comment by fwilhe2** [comment]
Any support to get this merged would be appreciated. Being able to use this natively on a m1 mac would be a great feature imo.

**Review by sumanmaity1234 — APPROVED** [review]

**Pull request merged**
